"""Increase ms_drg_definition field length to 255 characters

Revision ID: dd4c46ba12a3
Revises: 856091cd0b7c
Create Date: 2025-09-17 14:46:07.803002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4c46ba12a3'
down_revision = '856091cd0b7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drg_prices', 'ms_drg_definition',
                    existing_type=sa.VARCHAR(length=10),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drg_prices', 'ms_drg_definition',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.VARCHAR(length=10),
                    existing_nullable=False)
    # ### end Alembic commands ###
